name: Deploy to Elastic Beanstalk # Workflow name (shows in GitHub)

on:       # When to run
  push:
    branches:
      - main  # Only on pushes to main branch

jobs:
  deploy:   # Job name
    runs-on: ubuntu-latest # Virtual machine type (free Linux)

    steps:   # Sequential tasks
      - name: Checkout code   # Step description
        uses: actions/checkout@v3   # Pre-built action from GitHub

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Action to install Node.js
        with:
          node-version: '18'  # or your Node version

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test

      - name: Zip source code
        run: zip -r app.zip . -x "*.git*" "node_modules/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: weather-api
          environment_name: Weather-api-env 
          version_label: v-${{ github.run_number }}
          use_existing_version_if_available: true
          region: eu-north-1  # update to your actual region
          deployment_package: app.zip
